bot:
  commands_enabled: false
  plugins:
  - GamesKeeper.plugins.core
  - GamesKeeper.plugins.settings
  - GamesKeeper.plugins.stats
  - GamesKeeper.plugins.dev
  - GamesKeeper.plugins.connectfour
  - GamesKeeper.plugins.uno

first_run: true

#Channel that is used for logging control messages for the bot.
logging_channel: 000000000000

#Leave until fix is found for startup.
connect4_emotes:
  broken: true

postgres:
  host: 'localhost'
  port: '5432'
  database: 'gameskeeper'
  username: ''
  password: ''

token: 'BOT_TOKEN_HERE'

web:
  SECRET_KEY: ''
  DOMAIN: ''
  discord:
    CLIENT_ID: ''
    REDIRECT_URI: 'https://DOMAIN.COM/api/auth/discord/callback'
    CLIENT_SECRET: ''
    API_BASE_URL: 'https://discordapp.com/api'
    TOKEN_URL: 'https://discordapp.com/api/oauth2/token'
    AUTH_URL: 'https://discordapp.com/oauth2/authorize'
